env:
  browser: true
  commonjs: true
  node: true
extends: 'eslint:recommended'
rules:
  indent: 0
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
